### ISSUE TITLE
Broken on Paper 1.20.4

### ISSUE THREAD

**Issue by GEOEGII555** [ArcadiusMC/Grenadier#2]
This library appears to be broken on 1.20.4 `Paper version git-Paper-462 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 00fd87a)`. Here's the error:
<details><summary>Error</summary>
<pre>
[22:54:52 ERROR]: Caught previously unhandled exception :
[22:54:52 ERROR]: Paper Async Command Builder Thread Pool - 22
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_20_R2/command/VanillaCommandWrapper
        at net.forthecrown.grenadier.internal.GrenadierProviderImpl.createSource(GrenadierProviderImpl.java:88) ~[?:?]
        at net.forthecrown.grenadier.Grenadier.createSource(Grenadier.java:155) ~[?:?]
        at net.forthecrown.grenadier.internal.GrenadierBukkitWrapper.testPermissionSilent(GrenadierBukkitWrapper.java:39) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.test(BukkitCommandWrapper.java:56) ~[paper-1.20.4.jar:git-Paper-462]
        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.test(BukkitCommandWrapper.java:23) ~[paper-1.20.4.jar:git-Paper-462]
        at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:79) ~[paper-1.20.4.jar:git-Paper-462]
        at net.minecraft.commands.Commands.fillUsableCommands(Commands.java:535) ~[?:?]
        at net.minecraft.commands.Commands.sendAsync(Commands.java:493) ~[?:?]
        at net.minecraft.commands.Commands.lambda$sendCommands$6(Commands.java:466) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_20_R2.command.VanillaCommandWrapper
        at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 12 more
</pre></details>
Here's the command that I tried to register:
<details><summary>The command code</summary>
<pre lang="java">
@CommandData("""
name = 'modernrealisticelevators'
aliases = mre
executes = defaultExec()
""")
public class ElevatorsCommand {
    void defaultExec(CommandContext<CommandSource> context) {
        context.getSource().sendFailure(Component.text("test"));
    }
}
</pre></details>

The command doesn't work in the game either, it doesn't exist.

**Comment by GEOEGII555** [comment]
I've updated Paper to `Paper version git-Paper-463 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 45d1486)`, still broken.

**Comment by GEOEGII555** [comment]
Grenadier also broke the tab completion for commands. After sending the command, it works, but it's red in chat.
![изображение](https://github.com/ArcadiusMC/Grenadier/assets/57674559/30e0c58e-87df-4c71-a824-b8ab00aad257)

**Comment by JulieWoolie** [comment]
I'm sorry for not replying to this post earlier!
  
Are you using the latest version of Grenadier for 1.20.4 (grenadier-2.3.2)? I most likely made a mistake in the build process with an earlier version, apologies.

If changing versions doesn't help (or if you're already on the latest version), you can use `net.forthecrown:grenadier:2.3.2:reobf` as the dependency instead, that should fix the issue.

**Comment by GEOEGII555** [comment]
Adding this into dependencies worked:
```
<dependency>
      <groupId>net.forthecrown</groupId>
      <artifactId>grenadier</artifactId>
      <version>2.3.2</version>
      <scope>reobf</scope>
</dependency>
```
I also had to add net.kyori.adventure-api and add the normal `net.forthecrown:grenadier:2.3.2` into the libraries section of the plugin.yml for it to work.
![изображение](https://github.com/ArcadiusMC/Grenadier/assets/57674559/b6522fa5-7c04-41c3-8ac3-d0706c2b2b61)
